In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\downloads\ULTRA_LOW_LATENCY_TRADE_SIGNAL_ENGINE\BTCUSDT-trades-2025-08-02.csv")

In [3]:
df

,trade_id,price,qty,quote_qty,timestamp,is_buyer_maker,is_best_match
0,5127138383,113297.92,0.00882,999.287654,1754092800102922,True,True
1,5127138384,113297.93,0.00412,466.787472,1754092800258588,False,True
2,5127138385,113297.93,0.00444,503.042809,1754092800389151,False,True
3,5127138386,113297.92,0.13125,14870.352000,1754092800760072,True,True
4,5127138387,113297.93,0.01607,1820.697735,1754092800908577,False,True
...,...,...,...,...,...,...,...
1959327,5129097710,112886.19,0.00005,5.644310,1754171150019224,False,True
1959328,5129097711,112886.19,0.00005,5.644310,1754171150019224,False,True
1959329,5129097712,112886.19,0.00005,5.644310,1754171150019224,False,True
1959330,5129097713,112886.19,0.00009,10.159757,1754171150019224,False,True
1959331,5129097714,112886.19,0.00003,3.386586,1754171150019224,False,True

In [5]:
import pandas as pd
from tqdm import tqdm
from feature_engineering import FeatureEngineer  

# Load the CSV
df = pd.read_csv(r"C:\downloads\ULTRA_LOW_LATENCY_TRADE_SIGNAL_ENGINE\BTCUSDT-trades-2025-08-02.csv")

# Convert microsecond timestamp to human-readable string
df['timestamp_str'] = pd.to_datetime(df['timestamp'], unit='us').dt.strftime('%Y-%m-%d %H:%M:%S.%f')

# Initialize feature engineer with window=5
fe = FeatureEngineer(window=5)

# Store feature DataFrames
features_list = []

# Loop through each row simulating real-time processing
for _, row in tqdm(df.iterrows(), total=len(df)):
    price = float(row['price'])
    volume = float(row['qty'])
    timestamp_str = row['timestamp_str']

    fe.update(price=price, volume=volume, timestamp_str=timestamp_str)
    features = fe.compute_features()

    if features is not None:
        features_list.append(features)

# Combine all computed features
final_features_df = pd.concat(features_list, ignore_index=True)

# Save or inspect results
final_features_df.to_csv("computed_features_from_trades.csv", index=False)
print(final_features_df.head())

100%|██████████| 1959332/1959332 [18:51<00:00, 1732.04it/s]

                    timestamp  price_now      return_5  rolling_mean_5  \
0  2025-08-02 00:00:00.908577  113297.93  8.826287e-08      113297.926
1  2025-08-02 00:00:01.000853  113297.93  0.000000e+00      113297.928
2  2025-08-02 00:00:01.244230  113297.92 -8.826287e-08      113297.926
3  2025-08-02 00:00:01.244230  113297.92  0.000000e+00      113297.924
4  2025-08-02 00:00:01.244230  113297.92 -8.826287e-08      113297.924

   rolling_std_5  vwap_diff  volume_sum_5     rsi_5  tick_inter_arrival_time
0       0.004899  -0.009192       0.16470  50.00000                 0.000000
1       0.004000  -0.009144       0.15593  50.00000                 0.001412
2       0.004899   0.000605       0.15244  50.00000                 0.001412
3       0.004899   0.000324       0.14805  50.00000                 0.001412
4       0.004899   0.002843       0.01685   0.00001                 0.001412

In [6]:
df = pd.read_csv(r"C:\downloads\ULTRA_LOW_LATENCY_TRADE_SIGNAL_ENGINE\computed_features_from_trades.csv")
df.head(5)

,timestamp,price_now,return_5,rolling_mean_5,rolling_std_5,vwap_diff,volume_sum_5,rsi_5,tick_inter_arrival_time
0,2025-08-02 00:00:00.908577,113297.93,8.826287e-08,113297.926,0.004899,-0.009192,0.16470,50.00000,0.000000
1,2025-08-02 00:00:01.000853,113297.93,0.000000e+00,113297.928,0.004000,-0.009144,0.15593,50.00000,0.001412
2,2025-08-02 00:00:01.244230,113297.92,-8.826287e-08,113297.926,0.004899,0.000605,0.15244,50.00000,0.001412
3,2025-08-02 00:00:01.244230,113297.92,0.000000e+00,113297.924,0.004899,0.000324,0.14805,50.00000,0.001412
4,2025-08-02 00:00:01.244230,113297.92,-8.826287e-08,113297.924,0.004899,0.002843,0.01685,0.00001,0.001412